<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Analysis of Variance (ANOVA)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ANOVA_files/libs/clipboard/clipboard.min.js"></script>
<script src="ANOVA_files/libs/quarto-html/quarto.js"></script>
<script src="ANOVA_files/libs/quarto-html/popper.min.js"></script>
<script src="ANOVA_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ANOVA_files/libs/quarto-html/anchor.min.js"></script>
<link href="ANOVA_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ANOVA_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ANOVA_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ANOVA_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ANOVA_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis of Variance (ANOVA)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>Analysis of Variance (ANOVA)</strong>: A table that breaks down the sources of the variation (sums of squares) in the response variable, <span class="math inline">\(Y\)</span>, when we include explanatory variable(s), <span class="math inline">\(X_1, X_2, \cdots X_k\)</span>, in our linear model.</p>
<ul>
<li><strong>Total Sums of Squares</strong>: <span class="math inline">\(\text{SST} = (n-1) s_y^2 = \sum_{i=1}^n (y_i - \bar{y})^2\)</span></li>
</ul>
<p>Let’s see if we can break down <span class="math inline">\(\text{SST}\)</span> further:</p>
<p><span class="math display">\[
\sum_{i=1}^n (y_i - \bar{y})^2 = \sum_{i=1}^n (y_i - \hat{y}_i + \hat{y}_i - \bar{y})^2 = \sum_{i=1}^n (y_i - \hat{y}_i)^2 + \sum_{i=1}^n (\hat{y}_i - \bar{y})^2 + 2\sum_{i=1}^n (y_i - \hat{y}_i)(\hat{y}_i - \bar{y})
\]</span></p>
<p><strong>Note:</strong> <span class="math inline">\(\hat{y}_i\)</span> are predictions from a least squares regression line from a multiple linear regression model.</p>
<p>It can be proven that the final term on right is equal to 0 because <span class="math inline">\((y_i - \hat{y}_i)\)</span> and <span class="math inline">\((\hat{y}_i - \bar{y})\)</span> are orthogonal (independent). Therefore, <span class="math inline">\(\text{SST}\)</span> can be decomposed to:</p>
<p><span class="math display">\[
\sum_{i=1}^n (y_i - \bar{y})^2 = \sum_{i=1}^n (\hat{y}_i - \bar{y})^2 + \sum_{i=1}^n (y_i - \hat{y}_i)^2
\]</span></p>
<ul>
<li><p><strong>Sums of Squares for the Model</strong>: <span class="math inline">\(\text{SSM} = \sum_{i=1}^n (\hat{y}_i - \bar{y})^2\)</span></p>
<ul>
<li>SSM can be thought of as the variation in <span class="math inline">\(Y\)</span> that is explained by a linear regression model</li>
</ul></li>
<li><p><strong>Sums of Squared Errors</strong>: <span class="math inline">\(\text{SSE} = \sum_{i=1}^n ({y}_i - \hat{y}_i)^2\)</span></p>
<ul>
<li>SSE can be thought of as the variation in <span class="math inline">\(Y\)</span> that is not explained by a linear regression model.</li>
</ul></li>
<li><p><strong>Mean Squared for Model</strong>: The variance of <span class="math inline">\(Y\)</span> explained by the linear model</p></li>
</ul>
<p><span class="math display">\[\text{MSM} = \frac{\text{SSM}}{k-1},\]</span>where <span class="math inline">\(k - 1\)</span> is the <em>model degrees of freedom</em> for our linear model, and <span class="math inline">\(k\)</span> is the number of parameters (<span class="math inline">\(\beta\)</span>s) in our linear model. The model degrees of freedom can also be defined as the number of explanatory variables in our linear regression model.</p>
<ul>
<li><strong>Mean Squared Error</strong>: The variance of <span class="math inline">\(Y\)</span> not explained by the linear model</li>
</ul>
<p><span class="math display">\[\text{MSE} = \frac{\text{SSE}}{n-k},\]</span> where <span class="math inline">\(n - k\)</span> is the <em>error degrees of freedom</em> for our linear model.</p>
<ul>
<li>For simple linear regression, <span class="math inline">\(k=2\)</span>. Therefore, the model degrees of freedom is <span class="math inline">\(1\)</span> and the error degrees of freedom is <span class="math inline">\(n - 2\)</span>.</li>
</ul>
<p><strong>F Statistic</strong>: A statistic that measures the ratio of the variances of the response variable <span class="math inline">\(Y\)</span> that is explained/not explained by the model, <span class="math display">\[F = \frac{\text{MSM}}{\text{MSE}} = \frac{\text{SSM}/(k-1)}{\text{SSE}/(n-k)} = \frac{\text{Explained Variance}}{\text{Unexplained Variance}}\]</span></p>
<ul>
<li><p>If <span class="math inline">\(F\)</span> is significantly large, then we have more variance explained by the model than unexplained, which provides evidence that the linear regression model is significant.</p></li>
<li><p>For Simple linear regression, <span class="math display">\[F = \frac{\text{SSM}}{\text{SSE}/(n-2)} = \frac{\sum_{i=1}^n (\hat{y}_i - \bar{y})^2}{\hat{\sigma}^2} = \frac{\sum_{i=1}^n (\hat{\beta}_0 + \hat{\beta}_1 x_i - \bar{y})^2}{\hat{\sigma}^2}\]</span></p>
<p><span class="math display">\[
= \frac{\sum_{i=1}^n (\bar{y} - \hat{\beta}_1\bar{x} + \hat{\beta}_1x_i - \bar{y})^2}{\hat{\sigma}^2} = \frac{\hat{\beta}_1^2\sum_{i=1}^n (x_i - \bar{x})^2}{\hat{\sigma}^2} = \frac{\hat{\beta}_1^2 (n-1) s_x^2}{\hat{\sigma}^2} = \frac{\hat{\beta}_1^2}{\hat{\sigma}_{\hat{\beta}_1}^2} = t^2
\]</span></p></li>
</ul>
<p>Recall, if <span class="math inline">\(t \sim t_{df=\nu}\)</span>, then <span class="math inline">\(F = t^2 \sim F_{df1=1,df2=\nu}\)</span>. Then, we can equivalent say that, if we are testing for a significant linear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, the p-value would be calculated as <span class="math display">\[p-value = P(F_{df1=p-1,df2=n-p} &gt; F).\]</span></p>
<ul>
<li>For simple linear regression, calculating a p-value from <span class="math inline">\(t\)</span> using a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom is the same as calculating a p-value from <span class="math inline">\(F = t^2\)</span> using an F-distribution with <span class="math inline">\(df1=1\)</span> and <span class="math inline">\(df2=n-2\)</span>.</li>
<li>If <span class="math inline">\(p-value &lt; \alpha\)</span>, then we reject <span class="math inline">\(H_0\)</span> and say there is a significant linear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
<li>If <span class="math inline">\(p-value \geq \alpha\)</span>, then we fail to reject <span class="math inline">\(H_0\)</span> and say there is not a significant linear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
</ul>
<section id="anova-table-format" class="level2">
<h2 class="anchored" data-anchor-id="anova-table-format">ANOVA Table Format</h2>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">df</th>
<th style="text-align: left;">Sums of Squares</th>
<th style="text-align: left;">Mean Square</th>
<th style="text-align: left;">F Value</th>
<th style="text-align: left;">Pr(&gt;f)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td style="text-align: left;"><span class="math inline">\(k-1\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\text{SSM}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\text{MSM} = \frac{\text{SSM}}{k-1}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(F=\frac{\text{MSM}}{\text{MSE}}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(P(F_{df1=k-1,df2=n-k} &gt; F)\)</span></td>
</tr>
<tr class="even">
<td>Error</td>
<td style="text-align: left;"><span class="math inline">\(n-k\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\text{SSE}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\text{MSE} = \frac{\text{SSE}}{n-k}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: left;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\text{SST} = \text{SSM} + \text{SSE}\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<p>Fill in the following incomplete ANOVA table.</p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">df</th>
<th style="text-align: left;">Sums of Squares</th>
<th style="text-align: left;">Mean Square</th>
<th style="text-align: left;">F Value</th>
<th style="text-align: left;">Pr(&gt;f)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">50.83</td>
<td style="text-align: left;"><strong>50.83</strong></td>
<td style="text-align: left;"><strong>51.20</strong></td>
<td style="text-align: left;"><strong>4.246e-9</strong></td>
</tr>
<tr class="even">
<td>Error</td>
<td style="text-align: left;">48</td>
<td style="text-align: left;"><strong>47.65</strong></td>
<td style="text-align: left;"><strong>0.9927</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: left;"><strong>49</strong></td>
<td style="text-align: left;">98.48</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dfM <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dfE <span class="ot">&lt;-</span> <span class="dv">48</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>SSM <span class="ot">&lt;-</span> <span class="fl">50.83</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fl">98.48</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SST <span class="sc">-</span> SSM</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>SSE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 47.65</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>MSM <span class="ot">&lt;-</span> SSM <span class="sc">/</span> dfM</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSE <span class="sc">/</span> dfE</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>MSM</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50.83</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>MSE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9927083</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>F <span class="ot">&lt;-</span> MSM <span class="sc">/</span> MSE</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>F</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51.20336</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pf</span>(F,dfM,dfE,<span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.246413e-09</code></pre>
</div>
</div>
</section>
<section id="example-1" class="level2">
<h2 class="anchored" data-anchor-id="example-1">Example</h2>
<p>Using the bloodpressure dataset, obtain an ANOVA table and perform a hypothesis test for a significant linear relationship.</p>
<ul>
<li><p>Reduced Model: <span class="math inline">\(\hat{SBP} = \beta_0\)</span></p></li>
<li><p>Full Model: <span class="math inline">\(\hat{SBP} = \beta_0 + \beta_1 Age\)</span></p></li>
</ul>
<p><span class="math display">\[
H_0: \beta_1 = 0
\]</span></p>
<p><span class="math display">\[
H_a: \beta_1 \neq 0
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bloodpressure <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data/bloodpressure.csv"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> Age,bloodpressure)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SBP ~ Age, data = bloodpressure)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.724  -6.994  -0.520   2.931  75.654 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  98.7147    10.0005   9.871 1.28e-10 ***
Age           0.9709     0.2102   4.618 7.87e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.31 on 28 degrees of freedom
Multiple R-squared:  0.4324,    Adjusted R-squared:  0.4121 
F-statistic: 21.33 on 1 and 28 DF,  p-value: 7.867e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: SBP
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Age        1 6394.0  6394.0   21.33 7.867e-05 ***
Residuals 28 8393.4   299.8                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><span class="math inline">\(t = 4.618\)</span>, <span class="math inline">\(F = 21.33 = 4.618^2\)</span>, <span class="math inline">\(p = 7.867 \times 10^{-5}\)</span>. $p &lt; $, so we reject <span class="math inline">\(H_0\)</span>, so we conclude that we have statistically significant evidence of a linear relationship between age and systolic blood pressure.</p>
<p><strong>Bivariate Normal Distribution:</strong> A distribution that describes the joint relationship between two different normally distributed random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span></p>
</section>
<section id="parameters-of-bivariate-normal-distribution" class="level2">
<h2 class="anchored" data-anchor-id="parameters-of-bivariate-normal-distribution">Parameters of Bivariate Normal Distribution:</h2>
<ul>
<li><p><span class="math inline">\(\mu_X\)</span>: univariate mean of <span class="math inline">\(X\)</span></p></li>
<li><p><span class="math inline">\(\mu_Y\)</span>: univariate mean of <span class="math inline">\(Y\)</span></p></li>
<li><p><span class="math inline">\(\sigma_X^2\)</span>: univariate variance of <span class="math inline">\(X\)</span></p></li>
<li><p><span class="math inline">\(\sigma_Y^2\)</span>: univariate variance of <span class="math inline">\(Y\)</span></p></li>
<li><p><span class="math inline">\(\rho\)</span>: correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span></p></li>
</ul>
<p>A nice property of the bivariate normal distribution is that we can slice the distribution at a fixed value of <span class="math inline">\(X\)</span> to obtain the <em>conditional distribution</em> of <span class="math inline">\(Y\)</span> at a given value of <span class="math inline">\(X\)</span>. This distribution is also normally distributed with</p>
<ul>
<li><p><span class="math inline">\(\mu_{Y|X} = \mu_Y + \frac{\rho\sigma_Y}{\sigma_X}(X - \mu_X)\)</span> and</p></li>
<li><p><span class="math inline">\(\sigma_{Y|X}^2 = \sigma_Y^2(1 - \rho^2).\)</span></p></li>
</ul>
<p>Recall, in the simple linear regression notes, we also defined</p>
<ul>
<li><span class="math inline">\(\mu_{Y|X} = \beta_0 + \beta_1 X\)</span></li>
</ul>
<p>Combining the definitions of <span class="math inline">\(\mu_{Y|X}\)</span>, we can say that <span class="math display">\[\beta_1 = \frac{\rho \sigma_Y}{\sigma_X},\]</span></p>
<p>and another defintion of its estimate is <span class="math display">\[\hat{\beta}_1 = \frac{rs_y}{s_x}.\]</span></p>
<p>where <span class="math inline">\(r\)</span> is an estimate of the correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, more specifically the Pearson correlation coefficient, and <span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span> are the sample standard deviations of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p>We can also say that <span class="math display">\[\hat{\sigma}_{Y|X}^2 = \hat{\sigma}^2 = \frac{(n-1)s_y^2}{n-2}(1-r^2) = \frac{\text{SST}(1-r^2)}{n-2}\]</span></p>
<p><strong>Note:</strong> The <span class="math inline">\(n-1\)</span> and <span class="math inline">\(n-2\)</span> terms are adjustments for the error degrees of freedom</p>
<p><strong>R-Squared</strong>(<span class="math inline">\(r^2\)</span>): the percent of variation in the response variable <span class="math inline">\(Y\)</span> that can be explained through a linear relationship with the explanatory variables <span class="math inline">\(X_1,X_2,\cdots,X_k\)</span></p>
<p>Formally, <span class="math display">\[r^2 = \frac{\text{SSM}}{\text{SST}} = \frac{\text{SSM}}{\text{SSM} + \text{SSE}},\]</span></p>
<section id="example-2" class="level3">
<h3 class="anchored" data-anchor-id="example-2">Example</h3>
<p>Find the <span class="math inline">\(r^2\)</span> of the systolic blood pressure dataset. Interpret this value in the context of the given problem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4323947</code></pre>
</div>
</div>
<p>0.4324. 43.24% of the variation in systolic blood pressure can be explained through a linear relationship with age.</p>
<ul>
<li><p><span class="math inline">\(r^2\)</span> by itself cannot determine if a linear model is statistically significant</p></li>
<li><p>The more explanatory variables you add to the model, the higher the <span class="math inline">\(r^2\)</span> will go.</p></li>
</ul>
<p><strong>Note:</strong> We can use <span class="math inline">\(r^2\)</span> to calculate the <span class="math inline">\(F\)</span>-statistic in hypothesis testing!</p>
<p><span class="math display">\[
F = \frac{\text{SSM}/(k-1)}{\text{SSE}/(n-k)} = \frac{(\text{SSM}/\text{SST})/(k-1)}{(\text{SSE}/\text{SST})/(n-k)} = \frac{r^2/(k-1)}{(1 - r^2)/(n-k)}
\]</span></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>